### ISSUE TITLE
Add AppVeyor build and push to community MyGet for bleeding edge testers

### ISSUE THREAD

**Issue by Jeavon** [kgiszewski/uWestFest#38]
@kgiszewski are you happy for me to hook this up?

**Comment by Jeavon** [comment]
I have hooked this up now. AppVeyor builds and artifacts can be found at https://ci.appveyor.com/project/JeavonLeopold/uwestfest-x4mvd

**Comment by Jeavon** [comment]
@kgiszewski I've set this up to use Semver versioning, so CI builds will be like "0.16.0-alpha-1" and rtms will be like "0.16.0". The dll versioning will include the build number so 0.16.0.12 (this is also automated).

I haven't yet merged this to the master branch but that branch will be set to not have a suffix so every build from the master branch would be a rtm build.

Does that make sense and is it ok?

**Comment by kgiszewski** [comment]
Awesone thank you.
