### ISSUE TITLE
Property Converter Performance Issue

### ISSUE THREAD

**Issue by SayTen** [kgiszewski/uWestFest#41]
The use of the data type service in the updated property converter adds a small but noticable delay in resolving any properties.  Locally we're seeing a 60-80ms delay on using it.  We've used the URL Picker for a navigation builder for this particular site and when you output 15+ URLs into the navigation this builds into a significant time.  Is there a way to detect the requested type from within the property converter as this would likely be much quicker?

Or would a static cache of property to type that could be created at boot up be a better approach?

I don't mind doing the leg work but would appreciate input on best approach.

**Comment by Jeavon** [comment]
It's already memory cached, did you use the latest version from source?

**Comment by SayTen** [comment]
Sorry, just noticed that, must have accidently grabbed an old one earlier.  Mostly we use the nuget version.  Today is not being a good day ;/

**Comment by Jeavon** [comment]
No worries, think we are near a new release now #39 is resolved
