### ISSUE TITLE
Upgrading from 0.14 r to 0.15+ causes data corruption

### ISSUE THREAD

**Issue by Jeavon** [kgiszewski/uWestFest#46]
Data saved in 0.14 or before is like this:

```
{
  "type": "content",
  "meta": {
    "title": "",
    "newWindow": false
  },
  "typeData": {
    "url": "",
    "contentId": 1395,
    "mediaId": null
  }
}
```

0.15 and beyond expects:
```
[
{
  "type": "content",
  "meta": {
    "title": "",
    "newWindow": false
  },
  "typeData": {
    "url": "",
    "contentId": 1395,
    "mediaId": null
  }
}
]
```

This causes the Umbraco UI to go very wrong...

**Comment by Jeavon** [comment]
@bjarnef do you know the best method to resolve this?

**Comment by Jeavon** [comment]
My fix is to add this to the Init method

        // hack to update v0.14 or lower version items to new format
        var stringValue = JSON.stringify($scope.model.value);
        if (stringValue.substring(0, 1) === '{') {
            var newStringValue = "[" + JSON.stringify($scope.model.value) + "]";
            $scope.model.value = newStringValue;
        }

**Comment by bjarnef** [comment]
@Jeavon maybe you could also just check if `$scope.model.value` is an array.. if not create a new array.
If `$scope.model.value` is an object (and maybe eval against the defaultModel) then add it to empty (new) array and last update `$scope.model.value`.

**Comment by Jeavon** [comment]
@bjarnef I have committed this here https://github.com/kgiszewski/uWestFest/commit/6dca20e30ce574ee2c652f002c3d63e2b5ae73bf If you are able to revise and improve I would be overjoyed :)
