### ISSUE TITLE
Media restrictions for users not respected.

### ISSUE THREAD

**Issue by JohnBertelsen** [kgiszewski/uWestFest#47]
If a user only has access to a restricted section of the media tree, should the dialog treepicker not only show that? In the case of no other manual config restrictions anyway.

**Comment by kgiszewski** [comment]
We use the stock dialog picker, this may be a core question?

**Comment by JohnBertelsen** [comment]
I tried testing with core pickers, and they behave as you would expect. 
But when I use urlPicker, media goes directly to root media folder, even though user only has permissions in nested folder.

**Comment by JohnBertelsen** [comment]
In the url.picker.js as far as i can see, the `dialogService.mediaPicker` are missing some configs, like `startNodeId` and `openAtNodeId`.

I suspect the it should be `startNodeId: getStartNodeId(type)`.
But I'm not sure about the other one, because you have to hook into the `userService`,  but that is not injected yet?? 

Am i wrong in this??

**Comment by kgiszewski** [comment]
You might be right. The core documentation was poor/non-existent when  originally conceived a few years back.

**Comment by JohnBertelsen** [comment]
Well even now I haven't been able to find much documentation on what `dialogService.mediaPicker config` are available. But I did have a play, and can definitely make `startNodeId: getStartNodeId(type)` work, so that it respects backoffice restrictions at least.

But it's weird how the `content` picker just works, without much config, with regard to the user restriction anyway.
